---
functional:
  - Пользователь должен иметь возможность авторизоваться через Github
  - Пользователь должен иметь возможность авторизоваться через Discort
  - Пользователь должен иметь возможность зарегистрироваться и авторизоваться по логину и паролю
  - Пользователь должен иметь возможность восстановить пароль
  - Авторизованный пользователь должен иметь возможность создавать игру с выбором сложности, языка и времени прохождения игры
  - Пользователь должен иметь возможность проверить собственное решение неограниченное количество раз
  - Пользователь должен иметь возможность открыть гайд с описанием функционала в созданной игре (Show guide)
  - Пользователь должен иметь возможность возвращения в игру после вылета из неё
  - Пользователь должен иметь возможность написания кода в текстовом редакторе игры
  - Пользователь должен иметь возможность сбросить все изменения кода (Reset solution)
  - Пользователь должен иметь возможность запуска написанного кода (Run)
  - Пользователь должен иметь возможность сдаться во время игры (Give up)
  - Игра считается полностью законченной после выхода обоих игроков
  - Авторизованный пользователь должен иметь возможность отправлять сообщение в общий чат
  - Авторизованный пользователь должен иметь возможность отправлять сообщение в чат внутри игры
  - Авторизованный пользователь должен иметь возможность просматривать и редактировать свой профиль
  - Авторизованный пользователь должен иметь возможность приглашать других пользователей в  свою игру
  - Авторизованный пользователь должен иметь возможность принимать/отклонять приглашения на игру от других пользователей
  - Авторизованный пользователь должен иметь возможность присоединиться к открытой игре
  - Авторизованный пользователь должен иметь возможность присоединиться к просмотру турнира других игроков
  - Неавторизованный пользователь должен иметь возможность пройти "Простую битву"
  - Каждый игрок видит код своего соперника в режиме онлайн
  - Каждый игрок имеет кнопку для проверки своего решения
  - Количество попыток проверки решения неограниченно
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры  
  - Соперник (после поражения) может выйти, а может доиграть до конца
  - Победитель может выйти из игры по нажатию кнопки "exit", которая у него появилась
  - Когда оба игрока вышли, игра считается полностью законченной и удаляется из памяти
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (от 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - сайт должен соответствовать законодательству
  - Даты и время должны отображаться в часовом поясе пользователя (а не сервера)
  - Если пользователь вышел из системы, редактор кода должен сохранить написанный код в LocalStorage
  - Если задача решена неверно, кнопка "Отправить" должна блокироваться на 3 секунды во избежание flood'а
  - Если пользователь закрывает вкладку во время баттла, система должна сохранить его прогресс.
  - Использование протокола HTTPS
  - Адаптивная верстка
  - Предусмотрена проверка уникальности пользователей
